INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 5, 'NOVELA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 3, 'NOVELA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('1984', 'George Orwell', 7, 'CIENCIA_FICCION');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Un mundo feliz', 'Aldous Huxley', 4, 'CIENCIA_FICCION');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Dune', 'Frank Herbert', 6, 'CIENCIA_FICCION');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Fundación', 'Isaac Asimov', 5, 'CIENCIA_FICCION');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Breve historia del tiempo', 'Stephen Hawking', 3, 'HISTORIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Sapiens', 'Yuval Noah Harari', 8, 'HISTORIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Los pilares de la Tierra', 'Ken Follett', 4, 'HISTORIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Historia de dos ciudades', 'Charles Dickens', 2, 'HISTORIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Orgullo y prejuicio', 'Jane Austen', 6, 'ROMANCE');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Cumbres borrascosas', 'Emily Brontë', 3, 'ROMANCE');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Bajo la misma estrella', 'John Green', 5, 'ROMANCE');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('El amor en los tiempos del cólera', 'Gabriel García Márquez', 4, 'ROMANCE');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Drácula', 'Bram Stoker', 7, 'TERROR');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Frankenstein', 'Mary Shelley', 4, 'TERROR');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('El resplandor', 'Stephen King', 6, 'TERROR');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('It', 'Stephen King', 5, 'TERROR');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('El nombre del viento', 'Patrick Rothfuss', 6, 'FANTASIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('El hobbit', 'J.R.R. Tolkien', 8, 'FANTASIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Juego de tronos', 'George R.R. Martin', 7, 'FANTASIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('American Gods', 'Neil Gaiman', 3, 'FANTASIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Steve Jobs', 'Walter Isaacson', 4, 'BIOGRAFIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('El diario de Ana Frank', 'Ana Frank', 5, 'BIOGRAFIA');
INSERT INTO libros (titulo, autor, ejemplares, genero) VALUES ('Leonardo da Vinci', 'Walter Isaacson', 3, 'BIOGRAFIA');
